require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

pod 'react-native-sqlite-storage', :path => '../thirdparty/react-native-sqlite-storage'
pod 'react-native-fetch-blob', :path => '../thirdparty/react-native-fetch-blob'
pod 'ReactNativeNavigation', :path => '../thirdparty/react-native-navigation'
pod 'RNGestureHandler', :path => '../thirdparty/react-native-gesture-handler'

target 'WizNoteLiteMobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  target 'WizNoteLiteMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
    
  end  
end

target 'WizNoteLiteMobile-tvOS' do
  # Pods for WizNoteLiteMobile-tvOS

  target 'WizNoteLiteMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
